# Generated by Django 4.2.15 on 2025-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("website", models.URLField()),
                ("established", models.IntegerField()),
                ("country", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
