# Generated by Django 4.2.15 on 2025-10-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("isbn", models.CharField(max_length=17, unique=True)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("genre", models.CharField(max_length=100)),
                ("publication_year", models.IntegerField()),
                ("pages", models.IntegerField()),
                ("language", models.CharField(max_length=50)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("cover_image", models.URLField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="authors.author",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="publishers.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
